<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotificationService.Application\NotificationService.Application.csproj" />
    <ProjectReference Include="..\NotificationService.Providers\NotificationService.Providers.csproj" />
  </ItemGroup>

</Project>
